name: SyncWide OS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: ilammy/setup-nasm@v1.5.2
        - uses: actions/checkout@v4

        - name: Update Ubuntu
          run: sudo apt update
        
        - name: Install pre-dependencies
          run: sudo apt install build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo

        - name: Get Binutils
          run: wget https://ftp.gnu.org/gnu/binutils/binutils-2.42.tar.gz
        
        - name: Unpack Binutils
          run: tar -xvzf binutils-2.42.tar.gz
        
        - name: Create a directory for Binutils
          run: mkdir build-binutils
        
        - name: Enter then directory for Binutils
          run: cd build-binutils

        - name: Build Binutils
          run: ../binutils-2.42/configure --target=i686-elf --prefix="$HOME/opt/cross" --with-sysroot --disable-nls --disable-werror | make | make install | cd ..

        - name: Get GCC
          run: wget https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.gz

        - name: Unpack GCC
          run: tar -xvzf gcc-13.2.0.tar.gz
        
        - name: Download prerequisites for GCC
          run: cd gcc-13.2.0 && ./contrib/download_prerequisites        
        
        - name: Exit GCC directory
          run: cd ..
        
        - name: Create a dirctory to Build GCC
          run: mkdir build-gcc

        - name: Enter the directory for GCC
          run: cd build-gcc
        
        - name: Build GCC
          run: ../gcc-13.2.0/configure --target=i686-elf --prefix="$HOME/opt/cross" --disable-nls --enable-languages=c,c++ --without-headers
    
        - name: make all-gcc
          run: make all-gcc

        - name: make all-target-libgcc
          run: make all-target-libgcc

        - name: make install-gcc
          run: make install-gcc
        
        - name: make install-target-libgcc
          run: make install-target-libgcc

        - name: make clean
          run: make clean
    
        - name: make
          run: make
